name: iCare ApiGateway JWT Generator
description: Generate a JWT token to be used to authenticate requests to an iCare service via iCare ApiGateway
author: https://github.com/iCareWorld
requirements: []
configuration:
  properties:
    service:
      type: string
    stage:
      type: string
    expiration:
      type: number
  additionalProperties: false
