name: iCare ApiGateway JWT Generator
description: Generate a JTW token to be used to authenticate requests to an iCAre service via iCare ApiGateway
author: https://github.com/iCareWorld
requirements: []
configuration:
  properties:
    service:
      type: string
    expiration:
      type: number
  additionalProperties: false
